version: "3"
services:
  rr-app:
    image: "rr-app"
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - composer:/app/vendor
  rr-db:
    image: "rr-db"
    build: ./db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/sqldump.sql:/docker-entrypoint-initdb.d/sqldump.sql
# creating this volumn to overwrite the vendor folder
# the container will run composer install itself.
volumes:
  composer: