rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"
  static:
    dir: "."
    forbid: [""]
    allow: [".js"]
    request:
      input: "custom-header"
    response:
      output: "output-header"
  pool:
    num_workers: 4
  pool.debug: true

logs:
  mode: development
  level: error
  encoding: json
  file_logger_options:
    log_output: "test.log"
    max_size: 10

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php", ".go", ".md" ]
      dirs: [ "." ]